Feature/add milestone 2 and 3 friendship requirements
Bluette1/ror-social-scaffold pull request #2
Opened 2020-09-03 10:15 UTC by Bluette1

##### [Feature/add milestone 2 and 3 friendship requirements](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)
- Covers the following milestones
  - Social media website - Milestone: friendships v1
  - Social media website - Milestone: friendships v2
- Implement the required friendship features
  - Create the required models and associations
  - Add the necessary logic in the controllers
  - Modify the corresponding views 
- Add tests
- [Live demo](https://post-bk-app.herokuapp.com/)

2020-09-07 06:39 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

I hope you're doing well. Thank you for the job done so far.
However, there are some missing requirements

1. It's required, as you can read it [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone2/postgre.png), to use **Postgresql** from the beginning of the project. Kindly set it up.

2. Please, remove logics from views. Implement them in views helpers

3. Please, the `FriendRequest` table is not needed. Only `Friendship` table with a **`status`** will be sufficient. Kindly fix that first. It's the more important.

4 Your webapp must have a button to invite user to friendship on users list page and on single user page, as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png), however, it only appears in the User list page and misses in the Single user page. Kindly added it, please.

5. You did a really good job concerning tests. However, integration tests are missing. Kindly add them.
Access to page, no model creation, just navigate through each page, click on links, fill forms and submit them and check the results from the new page and your database.

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-09-07 06:39 UTC, maelfosso commented on app/views/users/show.html.erb
> +    <%= render 'add_or_accept_or_reject_friend' %>
Kindly remove logic from views. Please implemented them in views helpers.

2020-09-08 10:22 UTC, stratospherique requested changes
### Great Progress @Bluette1 :clap: However, there is still some requirements that weren't implemented. Check :arrow_down: 

#### Behaviour (Requried) :warning: 
* [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- When sending a friend request, the posts of the other user appear in the timeline automatically even though he didn't accept the friend request yet.
#### Tests
* [ ] Unit testing for some models is missing

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-09-08 10:22 UTC, stratospherique commented on app/models/user.rb
> +  has_many :friends, through: :friendships, source: :inverse_friend, dependent: :destroy
#### Implementation :warning: 
* [ ] User model `has_many :friendships` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [ ] User model `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

2020-09-08 11:14 UTC, Bluette1 commented
@maelfosso and @stratospherique, thank you very much for your review and feedback!

2020-09-08 14:53 UTC, Dandush03 commented
# Status: :rocket: Project Approved :rocket: 

### GOOD job applying the necesary changes. 
### Happy Coding :nerd_face: :computer:

2020-09-09 03:05 UTC, merged

2020-09-09 08:13 UTC, Bluette1 commented
@Dandush03, thank you very much for your review and feedback!